-- series_entries_position_uidx — one LIVE entry per (series_id, position).
-- Phase 2b of feat/series-integrity-mechanism, split out of 20260813010000.
--
-- ▌▌ THIS MIGRATION IS DEPLOYED LAST, AFTER THE RE-POINTED WEB APP HAS SHIPPED. ▌▌
-- ▌
-- ▌It is separated from `series.length` for one reason, and the reason is a hazard rather than
-- ▌tidiness. The DEPLOYED client's drag-reorder (`useMoveEntry` before Phase 2) applies a reorder
-- ▌as a LOOP of single-row PostgREST updates, each its own transaction. Entries passing through
-- ▌each other's positions commit intermediate colliding states, which this index rejects
-- ▌mid-flight — turning today's silently-tolerated inconsistency into a user-visible, PARTIALLY
-- ▌APPLIED reorder. `pnpm deploy:migrations` pushes every pending file at once, so leaving this
-- ▌in the same file as `series.length` meant that hazard was live for the entire gap between the
-- ▌migration push and the app deploy, however long that happened to be.
-- ▌
-- ▌Deploy order, and it is not optional:
-- ▌  1. 20260813010000 (series.length) + 20260814010000 (set_series_order) + 20260815010000
-- ▌  2. the web app carrying the re-pointed client (useMoveEntry -> set_series_order)
-- ▌  3. THIS FILE — and only once production satisfies it (see the precondition below)
-- ▌
-- ▌Owner ruling, Phase 2 report, 2026-08-09, revising the Phase 1 "alongside (or after)" ruling:
-- ▌"'after' is clearly the safer reading — I'd rather take the extra migration-management
-- ▌overhead than accept a live partially-applied-reorder hazard."
--
-- ── What the index asserts ──────────────────────────────────────────────────────────────────────
-- A series_entries row means "this slot in the reading order is filled" — one physical book, one
-- slot, regardless of how many formats the reader owns. So ghosts (book_id null) occupy the
-- uniqueness space deliberately; there is no book_id carve-out. Tombstones (removed_at set) are
-- excluded, because a removed slot must not block the position's reuse. This alone would have
-- caught the ACOTAR collision (two books both claiming #4) at write time.
--
-- Partial unique INDEX, not a constraint, and not by preference — probed against this database:
-- `alter table ... add constraint ... unique (...) where (...)` is a syntax error (42601); partial
-- UNIQUE constraints do not exist in Postgres. Same idiom as series_entries_book_uidx
-- (20260716010000_series_experience.sql:52).
--
-- Being an INDEX rather than a constraint also means it CANNOT be deferred (`set constraints`
-- raises 42704 against it — probed). That is what forces set_series_order's park-then-write pass;
-- see 20260814010000's header for the full probe table.
--
-- ── Precondition: production must already satisfy this ──────────────────────────────────────────
-- CREATE UNIQUE INDEX fails outright against violating rows — loud by design; nothing is dropped
-- or rewritten here. The owner ran docs/queries/series-position-collision-preview.sql against
-- production: exactly ONE collision in the entire library, A Court of Thorns and Roses position 4,
-- a ghost ("A Court of Wings and Ruin", book_id null, user_edited true) against the linked
-- "A Court of Frost and Starlight" entry. That one row is resolved through the staged incident-file
-- workflow (docs/queries/, owner-run) BEFORE this deploys — it is Phase 4's first correction, and
-- Frost-and-Starlight's owner-convention position of 3.5 is what frees position 4.

create unique index series_entries_position_uidx
  on public.series_entries (series_id, position)
  where removed_at is null;
